### PR TITLE
updated account creation page

### PR DESCRIPTION
**Pull request by chasty2**

### CODE REVIEW

**Comment by BreadYogurt** [comment]
Wouldn't "signup" be a better name for the page? It's way less characters.

**Comment by BreadYogurt** [comment]
Also, the signup is meant to be part of the index, not on its own page.

**Comment by chasty2** [comment]
I agree, figured I would get the form started

**Review by BreadYogurt — APPROVED** [review]
After merging #13 with develop and resolving the changes with this PR I think this is fine.

**Pull request merged**
